# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .godot/imported/

stages:
  - import-assets
  - tests
  - export

variables:
  EXPORT_NAME: test-export

# Open the editor to import assets in case the cache was empty or outdated
import-assets:
  stage: import-assets
  image: adrasteondev/godot-ci:mono-4.2.1
  script:
    - godot --headless --verbose --editor --quit

gdunit4:
  stage: tests
  image: adrasteondev/godot-ci:mono-4.2.1
  #image: sdggames/godot-test:4.2.1
  script:
    - apt-get update && apt-get install -y \
      libx11-dev \
      libxcursor-dev \
      libxinerama-dev \
      libxrandr-dev \
      libxi-dev \
      libglu1-mesa-dev \
      && rm -rf /var/lib/apt/lists/*

    - export GODOT_BIN=/usr/local/bin/godot
    - godot -e --path . -s res://addons/gdUnit4/bin/ProjectScanner.gd --headless --audio-driver Dummy
    - chmod u+x ./addons/gdUnit4/runtest.sh
    - xvfb-run --auto-servernum ./addons/gdUnit4/runtest.sh -a test --audio-driver Dummy --display-driver x11 --rendering-driver opengl3 --screen 0 --continue --verbose

windows:
  stage: export
  image: adrasteondev/godot-ci:mono-4.2.1
  script:
    - mkdir -v -p build/windows
    # Use "--headless --export-release" instead of "--export" with Godot 4
    - godot --headless -v --export-release "Windows Desktop" build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows