image: barichello/godot-ci:mono-4.2.1

stages:
  - export

variables:
  EXPORT_NAME: test-deploy

before_script:
  - mkdir -v -p build/windows

windows:
  stage: export
  script:
    - godot -v --export-release "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows