image: adrasteondev/godot-ci:mono-4.2.1

# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .godot/imported/

stages:
  - import-assets
  - test
  - export

variables:
  EXPORT_NAME: test-export

# Open the editor to import assets in case the cache was empty or outdated
import-assets:
  stage: import-assets
  script:
    - godot --headless --verbose --editor --quit

gdUnit:
  stage: test
  script:
    - export GODOT_BIN=/usr/local/bin/godot
    - ./addons/gdUnit4/runtest.sh -a test

windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    # Use "--headless --export-release" instead of "--export" with Godot 4
    - godot --headless -v --export-release "Windows Desktop" build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows